#this is curl part of workflow
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: appcd-curl-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: curlargocd
  arguments:
    parameters:
    - name: token
      value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NzgyOTEyOTEsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU3ODI5MTI5MSwic3ViIjoiYWRtaW4ifQ.O_WQAZ5R6Jdca3uZji6LVrmYY461feHGwRmhvDo0uUI"

  templates:
  - name: curlargocd
    steps:
    - - name: curl-create
        template: curl
          parameters:
          - name: method
            value: "POST"
          - name: url
            value: "192.168.48.12:31410/api/v1/applications"
          - name: body
            value: "{"metadata": {
    "name": "appsync3"
  },
  "spec": {
    "destination": {
      "namespace": "dafault",
      "server": "https://kubernetes.default.svc"
    },
    "source": {
      "path": "manifests",
      "repoURL": "https://github.com/Unshapendwarf/project1.git",
      "targetRevision": "HEAD"
    },
    "project": "default",
    "syncPolicy": null
  }
}"

    - - name: curl-validation
        template: createvalidation
        arguments:
          parameters:
          - name: response
            from: "{{steps.curl-create.outputs.result}}"

  - name: curl
    inputs:
      parameters:
      - name: method
      - name: url
      - name: token
      - name: body    # parameter declaration
    container:
      # run cowsay with that message input parameter as args
      image: curlimages/curl
      command: [sh, -c]
      args: ["curl -X {{inputs.parameters.method}} https://{{inputs.parameters.url}} -H "Authorization: Bearer {{inputs.parameters.token}}" -d {{inputs.parameters.body}} -k -L"]
      #args: ["{{inputs.parameters.message}}"]

  - name: createvalidation
    inputs:
      parameters:
      - name: response
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo result was: {{inputs.parameters.response}}"]
  #- name: curlupdate
  #일단 여기 탬플릿에 뭐가 들어갈지는 나중에...
